import Image from 'next/image'
import { BusinessPresetCard, CampaignPresetCard, CardBorder } from '@/components'
import { IGeneratedAdData } from '@/types'

interface IGeneratedAdCardProps {
  ad: IGeneratedAdData
}

export const AdCard = ({ ad }: IGeneratedAdCardProps) => {
  return (
    <CardBorder className="w-full p-8 md:p-6 mb-12 md:flex-row md:items-start space-y-6 md:space-y-0 md:space-x-8">
      {ad.image_url && (
        <div className="w-full flex-shrink-0 md:w-1/3">
          <Image
            alt={`Ad for ${ad.business_details?.name || 'N/A'}`}
            className="rounded-md"
            height={300}
            src="https://hfdfggwxdvdykpeaxguf.supabase.co/storage/v1/object/public/marketing-assets/ad_image_5_26_1756019715820.png"
            width={300}
          />
          <div className="text-xs text-gray-500 mt-8">
            Generated by: {ad.generation_model} on {new Date(ad.created_at).toLocaleDateString()}
          </div>
        </div>
      )}
      <div className="flex-grow text-center md:text-left">
        <p className="text-sm flex-grow mb-4">{ad.ad_text}</p>
        <h3 className="text-lg font-semibold mb-2">Business Details</h3>
        <BusinessPresetCard businessPresetData={ad.business_details} />
        <h3 className="text-lg font-semibold mt-4 mb-2">Campaign Details</h3>
        <CampaignPresetCard campaignPresetData={ad.campaign_details} />
      </div>
    </CardBorder>
  )
}
